version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_todo_db
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: todo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_network

volumes:
  db_data:

networks:
  todo_network:
